server:
  port: 8080

spring:
  application:
    name: ip-query-service
  r2dbc:
    url: r2dbc:postgresql://ep-little-credit-a5igu90d-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: iJW9k5QERrhy
  contentmoderator:
    token: 0194073900d22b
